### ISSUE TITLE
Research Heroku with Multiple Contributors

### ISSUE THREAD

**Issue by kjs222** [robbiejaeger/little_shop#2]
How do we all get it as a remote
How do we all have ability to push to heroku

**Comment by kjs222** [comment]
https://devcenter.heroku.com/articles/collaborating

person that created the heroku app  should do this in command line from project directory:
`heroku access:add joe@example.com`

to confirm,  type this: `heroku access`
 should see all of the collaborators

the other people should do this after they've been added (falling-wind-1624 -- replace with our actual app name)
`heroku git:remote -a falling-wind-1624`

**Comment by robbiejaeger** [comment]
Thanks for looking into this. Seems pretty straight forward.  I will create the heroku site and then add everyone to it.
