### ISSUE TITLE
Retired Families

### ISSUE THREAD

**Issue by Carmer** [robbiejaeger/little_shop#44]
As a user if I visit an family page and that family is not current
      Then I should still be able to access the family page
      And I should not be able to add the donation to their cart
      And I should see in place of the "Add to Cart" button or link - "Family arrived"

**Comment by robbiejaeger** [comment]
A retired family means the arrival date is not in the past.

The impact of them being retired is:
- the family show page should not show the supply_item form
- instead, it should show the items that the family received
- retired families should be removed from the family index and category index
